# Generated by Django 3.0.4 on 2020-03-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='projected_winnings',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
